Header header

# voltage
float32 Voltage

# current
float32 Current

# residualCapacity
int32 ResidualCapacity

# DesignCapacity
int32 DesignCapacity

# CycleIndex
int16 CycleIndex

# DataProduction
string DataProduction

# StatusBalance
uint32 StatusBalance

# StatusProtect
uint16 StatusProtect

# Version
uint16 Version

# Rsoc
int16 Rsoc

# StatueMos
int16 StatueMos

# CellNumber
int16 CellNumber

# NtcNumber
int16 NtcNumber

# NtcTem
float64[] NtcTem

# CellVoltage
float64[] CellVoltage

# ErrorId
int64[] ErrorId

# ErrorInfo
string[] ErrorInfo